import Header from '@/component/Header';
import './globals.css';

export const metadata = {
  title: 'Amazon 2.0',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
